### ISSUE TITLE
Not syncing reliably with DropBox. Got this error.

### ISSUE THREAD

**Issue by mimetic** [coronalabs/CoronaViewer#1]
Not syncing reliably with DropBox. Got this error.
Jul  4 14:33:48 David-Grosss-iPad-3 CoronaViewer[5189] <Warning>: [ERROR] DropboxSDK: unable to link; app isn't registered for correct URL scheme (db-l1q0pln8qsi8qyp)

**Comment by Shchvova** [comment]
This should be better in latest version. Error message you posted is unrelated.
