### ISSUE TITLE
iOS8 + location bug 

### ISSUE THREAD

**Issue by raremedia** [coronalabs/CoronaViewer#2]
More information: http://forums.coronalabs.com/topic/53195-ios8-location-bug/

I wanted to mention a bug I've come across in CoronaViewer building against iOS8. As you may know iOS8 requires 'NSLocationWhenInUseUsageDescription' to be defined in the build settings which I had done in my app.

While developing I started noticing that my app in CoronaViewer was silent failing when the app attempted to use location functions.  Then I remembered that I needed to rebuild CoronaViewer with 'NSLocationWhenInUseUsageDescription' in it's copy of build settings too, which I did.

Now when I try to build CoronaViewer I get the following error message:
"
Unexpected build error.

Error code: 5

If you are not connecting to the internet directly (for example, you connect via a proxy server) you might want to try a direct connection to see if that solves the problem.

Check the console for more information.
"

When I remove the 'NSLocationWhenInUseUsageDescription' from the build settings the app builds perfectly fine.

**Comment by Shchvova** [comment]
This should be fixed in latest version.
